export {default as Navbar} from "./Navbar"
export {default as Hero} from "./Hero"
export {default as Stats} from "./Stats"
export {default as Service} from "./Service"
export {default as Card} from "./Card"
export {default as Testimonial}from "./Testimonial"
export {default as Partners} from "./Partners"
export {default as Cta} from"./Cta"
export {default as Footer} from "./Footer"
